pdf:
	jupyter nbconvert FinalReport.ipynb --to pdf --template=hide_header && open FinalReport.pdf

tex:
	jupyter nbconvert FinalReport.ipynb --to latex

progress:
	jupyter nbconvert ProgressReport.ipynb --to pdf --template=hide_header && open ProgressReport.pdf
