name: Black check

on: [push, pull_request]

jobs:
  black-check:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - uses: actions/checkout@v3
        name: Set up Python
      - uses: actions/setup-python@master
        with:
          python-version: 3.10.7
      - name: install black
        run: |
          pip install black==22.3.0
      - uses: actions/checkout@v3
      - name: run black
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: true
          version: "22.3.0"